name: Delete Old Files

on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    name: delete old files
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl --request DELETE \
          --url 'https://image-compressor-mvp.herokuapp.com/deleteOldFiles' \
          --header 'Authorization: Bearer ${{ secrets.DELETE_OLD_FILES_KEY }}'
